event_start: '2014-10-25T10:00:00+02:00'

participants:
  - blnight
  - teon
  - radoslawhryciow
  - afterdesign
  - slawekp
  - JoannaTrelaZielinska
  - MaciejCzyzewski
  - kontramedia
  - mpowroznik
  - tomkowz
  - piotrbulinski
  - sjedruszkiewicz
  - kmk2000
